.TH gtkhx 1 
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
gtkhx \- A GTK+ Hotline Client.
.SH SYNOPSIS
.B gtkhx [options]
.SH DESCRIPTION

.B gtkhx
is a GTK+ version of Hx, a UNIX Hotline Client
.SH OPTIONS
.B --help, -h		
Print out help.
.PP
.B --server, -s <host>	
Connect to <host>.
.PP
.B --port, -t <port>	
Connect to <host> on <port> (default: 5500)
.PP
.B --login, -l <login>	
Use <login> for <host> (default: guest)
.PP
.B --pass, -p		
Prompt for pass of <login>
.PP
.B --bookmark, -b		
Connect using bookmark <name>

.SH AUTHOR
This manual page was written by Misha Nasledov <misha@nasledov.com>
